#!/usr/bin/env bash
# Installs Nginx and configures a permanent redirect for /redirect_me

apt-get update -y
apt-get install -y nginx
mkdir -p /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html
sed -i '/server_name _;/a \\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx restart
